name: tests

on: [push, pull_request]

jobs:
  run-tests:
    name: test the codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build docker images
        run: docker-compose -f ./tests/docker-compose-test.yaml build

      - name: Run tests
        run: docker-compose -f ./tests/docker-compose-test.yaml run test
